name: Validate C++

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint-cpp.yml'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.mm'
  pull_request:
    paths:
      - '.github/workflows/lint-cpp.yml'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.mm'

jobs:
  lint:
    name: Check clang-format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
        - 'packages/react-native-nitro-modules/android/src/main/cpp'
        - 'packages/react-native-nitro-modules/cpp'
        - 'packages/react-native-nitro-modules/ios'
        - 'packages/react-native-nitro-image/android/src/main/cpp'
        - 'packages/react-native-nitro-image/cpp'
        - 'packages/react-native-nitro-image/ios'
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install --frozen-lockfile

      - name: Run clang-format style check
        uses: mrousavy/clang-format-action@v1
        with:
          clang-format-version: '16'
          check-path: ${{ matrix.path }}
          clang-format-style-path: .clang-format

