name: Lint C++

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint-cpp.yml'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.mm'
      - 'scripts/clang-format.sh'
  pull_request:
    paths:
      - '.github/workflows/lint-cpp.yml'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.mm'
      - 'scripts/clang-format.sh'

jobs:
  lint:
    name: Format C++
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2

      - name: Run clang-format
        run: bun run lint-cpp

      - name: Verify no files have changed after format
        run: git diff --exit-code HEAD -- . ':(exclude)bun.lock'

